/*
 * This file is generated by jOOQ.
 */
package com.tesis.resilientest.database.model.tables.records;


import com.tesis.resilientest.database.model.tables.DomPage;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DomPageRecord extends UpdatableRecordImpl<DomPageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>dom_page.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>dom_page.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>dom_page.url</code>.
     */
    public void setUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>dom_page.url</code>.
     */
    public String getUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>dom_page.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>dom_page.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>dom_page.screen_height</code>.
     */
    public void setScreenHeight(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>dom_page.screen_height</code>.
     */
    public Integer getScreenHeight() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>dom_page.screen_width</code>.
     */
    public void setScreenWidth(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>dom_page.screen_width</code>.
     */
    public Integer getScreenWidth() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>dom_page.viewport_height</code>.
     */
    public void setViewportHeight(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>dom_page.viewport_height</code>.
     */
    public Integer getViewportHeight() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>dom_page.viewport_width</code>.
     */
    public void setViewportWidth(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>dom_page.viewport_width</code>.
     */
    public Integer getViewportWidth() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>dom_page.full_page_screenshot_path</code>.
     */
    public void setFullPageScreenshotPath(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>dom_page.full_page_screenshot_path</code>.
     */
    public String getFullPageScreenshotPath() {
        return (String) get(7);
    }

    /**
     * Setter for <code>dom_page.content</code>.
     */
    public void setContent(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>dom_page.content</code>.
     */
    public String getContent() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DomPageRecord
     */
    public DomPageRecord() {
        super(DomPage.DOM_PAGE);
    }

    /**
     * Create a detached, initialised DomPageRecord
     */
    public DomPageRecord(Integer id, String url, String description, Integer screenHeight, Integer screenWidth, Integer viewportHeight, Integer viewportWidth, String fullPageScreenshotPath, String content) {
        super(DomPage.DOM_PAGE);

        setId(id);
        setUrl(url);
        setDescription(description);
        setScreenHeight(screenHeight);
        setScreenWidth(screenWidth);
        setViewportHeight(viewportHeight);
        setViewportWidth(viewportWidth);
        setFullPageScreenshotPath(fullPageScreenshotPath);
        setContent(content);
        resetChangedOnNotNull();
    }
}
