/*
 * This file is generated by jOOQ.
 */
package com.tesis.resilientest.database.model.tables.records;


import com.tesis.resilientest.database.model.tables.WebElement;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WebElementRecord extends UpdatableRecordImpl<WebElementRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>web_element.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>web_element.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>web_element.id_attribute</code>.
     */
    public void setIdAttribute(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>web_element.id_attribute</code>.
     */
    public String getIdAttribute() {
        return (String) get(1);
    }

    /**
     * Setter for <code>web_element.class_name</code>.
     */
    public void setClassName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>web_element.class_name</code>.
     */
    public String getClassName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>web_element.tag</code>.
     */
    public void setTag(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>web_element.tag</code>.
     */
    public String getTag() {
        return (String) get(3);
    }

    /**
     * Setter for <code>web_element.name</code>.
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>web_element.name</code>.
     */
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>web_element.href</code>.
     */
    public void setHref(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>web_element.href</code>.
     */
    public String getHref() {
        return (String) get(5);
    }

    /**
     * Setter for <code>web_element.alt</code>.
     */
    public void setAlt(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>web_element.alt</code>.
     */
    public String getAlt() {
        return (String) get(6);
    }

    /**
     * Setter for <code>web_element.full_xpath</code>.
     */
    public void setFullXpath(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>web_element.full_xpath</code>.
     */
    public String getFullXpath() {
        return (String) get(7);
    }

    /**
     * Setter for <code>web_element.relative_xpath</code>.
     */
    public void setRelativeXpath(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>web_element.relative_xpath</code>.
     */
    public String getRelativeXpath() {
        return (String) get(8);
    }

    /**
     * Setter for <code>web_element.inner_text</code>.
     */
    public void setInnerText(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>web_element.inner_text</code>.
     */
    public String getInnerText() {
        return (String) get(9);
    }

    /**
     * Setter for <code>web_element.location_x</code>.
     */
    public void setLocationX(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>web_element.location_x</code>.
     */
    public Integer getLocationX() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>web_element.location_y</code>.
     */
    public void setLocationY(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>web_element.location_y</code>.
     */
    public Integer getLocationY() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>web_element.width</code>.
     */
    public void setWidth(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>web_element.width</code>.
     */
    public Integer getWidth() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>web_element.height</code>.
     */
    public void setHeight(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>web_element.height</code>.
     */
    public Integer getHeight() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>web_element.area</code>.
     */
    public void setArea(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>web_element.area</code>.
     */
    public Integer getArea() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>web_element.shape</code>.
     */
    public void setShape(Float value) {
        set(15, value);
    }

    /**
     * Getter for <code>web_element.shape</code>.
     */
    public Float getShape() {
        return (Float) get(15);
    }

    /**
     * Setter for <code>web_element.is_button</code>.
     */
    public void setIsButton(Boolean value) {
        set(16, value);
    }

    /**
     * Getter for <code>web_element.is_button</code>.
     */
    public Boolean getIsButton() {
        return (Boolean) get(16);
    }

    /**
     * Setter for <code>web_element.last_valid_type_selector</code>.
     */
    public void setLastValidTypeSelector(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>web_element.last_valid_type_selector</code>.
     */
    public String getLastValidTypeSelector() {
        return (String) get(17);
    }

    /**
     * Setter for <code>web_element.last_valid_selector</code>.
     */
    public void setLastValidSelector(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>web_element.last_valid_selector</code>.
     */
    public String getLastValidSelector() {
        return (String) get(18);
    }

    /**
     * Setter for <code>web_element.element_screenshot_path</code>.
     */
    public void setElementScreenshotPath(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>web_element.element_screenshot_path</code>.
     */
    public String getElementScreenshotPath() {
        return (String) get(19);
    }

    /**
     * Setter for <code>web_element.neighbor_elements</code>.
     */
    public void setNeighborElements(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>web_element.neighbor_elements</code>.
     */
    public String getNeighborElements() {
        return (String) get(20);
    }

    /**
     * Setter for <code>web_element.neighbor_elements_text</code>.
     */
    public void setNeighborElementsText(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>web_element.neighbor_elements_text</code>.
     */
    public String getNeighborElementsText() {
        return (String) get(21);
    }

    /**
     * Setter for <code>web_element.dom_page_id</code>.
     */
    public void setDomPageId(Integer value) {
        set(22, value);
    }

    /**
     * Getter for <code>web_element.dom_page_id</code>.
     */
    public Integer getDomPageId() {
        return (Integer) get(22);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WebElementRecord
     */
    public WebElementRecord() {
        super(WebElement.WEB_ELEMENT);
    }

    /**
     * Create a detached, initialised WebElementRecord
     */
    public WebElementRecord(Integer id, String idAttribute, String className, String tag, String name, String href, String alt, String fullXpath, String relativeXpath, String innerText, Integer locationX, Integer locationY, Integer width, Integer height, Integer area, Float shape, Boolean isButton, String lastValidTypeSelector, String lastValidSelector, String elementScreenshotPath, String neighborElements, String neighborElementsText, Integer domPageId) {
        super(WebElement.WEB_ELEMENT);

        setId(id);
        setIdAttribute(idAttribute);
        setClassName(className);
        setTag(tag);
        setName(name);
        setHref(href);
        setAlt(alt);
        setFullXpath(fullXpath);
        setRelativeXpath(relativeXpath);
        setInnerText(innerText);
        setLocationX(locationX);
        setLocationY(locationY);
        setWidth(width);
        setHeight(height);
        setArea(area);
        setShape(shape);
        setIsButton(isButton);
        setLastValidTypeSelector(lastValidTypeSelector);
        setLastValidSelector(lastValidSelector);
        setElementScreenshotPath(elementScreenshotPath);
        setNeighborElements(neighborElements);
        setNeighborElementsText(neighborElementsText);
        setDomPageId(domPageId);
        resetChangedOnNotNull();
    }
}
