/*
 * This file is generated by jOOQ.
 */
package com.tesis.resilientest.database.model;


import com.tesis.resilientest.database.model.tables.DomPage;
import com.tesis.resilientest.database.model.tables.WebElement;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>dom_page</code>.
     */
    public final DomPage DOM_PAGE = DomPage.DOM_PAGE;

    /**
     * The table <code>web_element</code>.
     */
    public final WebElement WEB_ELEMENT = WebElement.WEB_ELEMENT;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            DomPage.DOM_PAGE,
            WebElement.WEB_ELEMENT
        );
    }
}
