/*
 * This file is generated by jOOQ.
 */
package com.tesis.resilientest.database.model;


import com.tesis.resilientest.database.model.tables.DomPage;
import com.tesis.resilientest.database.model.tables.WebElement;
import com.tesis.resilientest.database.model.tables.records.DomPageRecord;
import com.tesis.resilientest.database.model.tables.records.WebElementRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DomPageRecord> DOM_PAGE__PK_DOM_PAGE = Internal.createUniqueKey(DomPage.DOM_PAGE, DSL.name("pk_dom_page"), new TableField[] { DomPage.DOM_PAGE.ID }, true);
    public static final UniqueKey<WebElementRecord> WEB_ELEMENT__PK_WEB_ELEMENT = Internal.createUniqueKey(WebElement.WEB_ELEMENT, DSL.name("pk_web_element"), new TableField[] { WebElement.WEB_ELEMENT.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<WebElementRecord, DomPageRecord> WEB_ELEMENT__FK_WEB_ELEMENT_PK_DOM_PAGE = Internal.createForeignKey(WebElement.WEB_ELEMENT, DSL.name("fk_web_element_pk_dom_page"), new TableField[] { WebElement.WEB_ELEMENT.DOM_PAGE_ID }, Keys.DOM_PAGE__PK_DOM_PAGE, new TableField[] { DomPage.DOM_PAGE.ID }, true);
}
