/*
 * This file is generated by jOOQ.
 */
package com.tesis.resilientest.database.model;


import com.tesis.resilientest.database.model.tables.DomPage;
import com.tesis.resilientest.database.model.tables.WebElement;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>dom_page</code>.
     */
    public static final DomPage DOM_PAGE = DomPage.DOM_PAGE;

    /**
     * The table <code>web_element</code>.
     */
    public static final WebElement WEB_ELEMENT = WebElement.WEB_ELEMENT;
}
